Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -4,8 +4,9 @@ pipeline {
     environment {
         DOCKER_IMAGE = '211125528700.dkr.ecr.us-west-2.amazonaws.com/rheo-flask-app:latest'
         REGISTRY_URL = '211125528700.dkr.ecr.us-west-2.amazonaws.com/rheo-flask-app'
-        TARGET_VM_HOST = '35.165.99.46'
+        TARGET_VM_HOST = '35.165.99.46' // Replace with your target VM IP address
         SSH_CREDENTIALS_ID = 'targetvm' // Replace with your Jenkins SSH credentials ID
+        AWS_REGION = 'us-west-2'
     }
 
     stages {
@@ -22,7 +23,7 @@ pipeline {
             steps {
                 script {
                     // Log in to the Docker registry
-                    sh "aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 211125528700.dkr.ecr.us-west-2.amazonaws.com"
+                    sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${REGISTRY_URL}"
                     // Push the Docker image to the registry
                     sh "docker push ${DOCKER_IMAGE}"
                 }
@@ -32,19 +33,15 @@ pipeline {
         stage('Deploy to Target VM') {
             steps {
                 script {
-                    // Log in to the Docker registry on the target VM
+                    // Log in to the target VM and pull the Docker image
                     sshagent(credentials: [SSH_CREDENTIALS_ID]) {
                         sh """
-                            ssh -o StrictHostKeyChecking=no ubuntu@${TARGET_VM_HOST} 'aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 211125528700.dkr.ecr.us-west-2.amazonaws.com'
-                        """
-                    }
-                    // Pull the Docker image on the target VM and run it
-                    sshagent(credentials: [SSH_CREDENTIALS_ID]) {
-                        sh """
-                            ssh -o StrictHostKeyChecking=no ubuntu@${TARGET_VM_HOST} '
-                                docker pull ${DOCKER_IMAGE}
-                                docker run -d -p 80:5000 ${DOCKER_IMAGE}
-                            '
+                        ssh -o StrictHostKeyChecking=no ubuntu@${TARGET_VM_HOST} '
+                        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${REGISTRY_URL} && 
+                        docker pull ${DOCKER_IMAGE} && 
+                        docker stop rheo-flask-app || true && 
+                        docker rm rheo-flask-app || true && 
+                        docker run -d --name rheo-flask-app -p 80:5000 ${DOCKER_IMAGE}'
                         """
                     }
                 }
@@ -54,16 +51,16 @@ pipeline {
 
     post {
         always {
-            // Clean up Docker images after the build
             script {
+                // Clean up Docker images on Jenkins agent after the build
                 sh "docker rmi ${DOCKER_IMAGE}"
             }
         }
         success {
-            echo 'The build was successful!'
+            echo 'The build and deployment were successful!'
         }
         failure {
-            echo 'The build failed.'
+            echo 'The build or deployment failed.'
         }
     }
 }
